### ISSUE TITLE
Редактирование количества купленого товара

### ISSUE THREAD

**Issue by VZhyrytskiy** [RedFoxIK/shop#5]
Все с заданием хорошо, но у вас нет функционала по редактированию количества купленого товара. Сейчас больше одного товара не купить. Понимаю, что ваши товары врядли покупаются большими количествами, но в реальном магазине есть возможность задать количество товара для покупки.

**Comment by RedFoxIK** [comment]
Спасибо, исправлю в следующем домашнем задании
